language: node_js
node_js:
  - 8
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ #also run on tags

addons:
  apt:
    update: true
    packages:
      - jq

cache:
  directories:
    - node_modules

install:
  - npm install esdoc esdoc-standard-plugin esdoc-ecmascript-proposal-plugin karma karma-jasmine karma-firefox-launcher karma-chrome-launcher jasmine-core karma-coverage

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - karma start --single-run --browsers Firefox

before_deploy:
  - ./node_modules/.bin/esdoc
  - ./build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master
