language: node_js
node_js:
  - '8'

addons:
  apt:
    update: true
    packages:
      - jq
  chrome: stable

cache:
  directories:
    - node_modules

install:
  - npm install esdoc esdoc-standard-plugin esdoc-ecmascript-proposal-plugin karma karma-jasmine karma-firefox-launcher karma-chrome-launcher jasmine-core karma-coverage google-closure-compiler web-ext

services:
    - xvfb

script:
  - karma start --single-run --browsers Firefox
  - ./build.sh $TRAVIS_TAG

before_deploy:
  - ./node_modules/.bin/esdoc

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    local_dir: docs
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*.*
    skip_cleanup: true
    on:
      tags: true
